#!/usr/bin/perl

# paj gen.api context apimodule  struct_fields[description:textarea file:file]
# paj gen.api ShopContext ProductAd name:text description:textarea file:file
# paj gen.api context apimodule:apimodule_lc  struct_fields[description:textarea file:file]
# paj gen.api ShopContext ProductAd:product_ad name:text description:textarea file:file

# Run formatter for all files in the project

use lib "lib";

# use lib "lib", "/home/pande/bin/lib";

use Regex::Regex;

$resource_type = $ARGV[0];
$context       = $ARGV[1];
@fields        = @ARGV[ 3 .. ( scalar(@ARGV) - 1 ) ];

# Variable
$api_module = $ARGV[2];

# $api_module_lc          = lc($api_module);
$module_file_name       = lc($api_module);
$api_module_lc_plural   = lc($api_module);    # s is added dynamically
$api_module_lc_singular = lc($api_module);

# Default don`t include uploaded file receiving
$has_file = 0;

if ( $api_module =~ /(\b.*)y/ ) {
    print("True $api_module $1  :   $2\n");

    # $api_module = $1;
    $api_module_lc_plural   = lcfirst("${1}ies");    # s is added dynamically
    $api_module_lc_singular = lcfirst("${1}y");      # s is added dynamically
    $module_file_name       = lcfirst("${1}ies");

}

if ( $api_module =~ /(\b.*):(\b.*)/ ) {
    print("True $api_module $1  :   $2\n");
    $api_module       = $1;
    $module_file_name = $2;

    if ( $module_file_name =~ /(\b.*)y/ ) {
        print("True $module_file_name $1  :   $2\n");

        # $api_module = $1;
        $api_module_lc_plural   = lcfirst("${1}ies");   # s is added dynamically
        $api_module_lc_singular = lcfirst("${1}y");     # s is added dynamically
        $module_file_name       = lcfirst("${1}ies");

    }
    else {
        $api_module_lc_plural = lc("${module_file_name}s");

        # s is added dynamically
        $api_module_lc_singular =
          lc("${module_file_name}");                    # s is added dynamically
        $module_file_name = lc("${module_file_name}s");
    }

}

# print "$resource_type $context $api_module @fields \n";

if (   $resource_type eq "help"
    or $resource_type eq "-h"
    or $resource_type eq "--help" )
{
    $help = qq{
        ## Phoenix Elixir API generator aka paj

        # Syntax
        paj gen.api:[has_file] context module [fields ...]
        has_file -> boolean field generates files with acceptance of a file uploaded to the server


        Example:
        ``` $ paj gen.api ShopContext Product name description ```

        context -> ShopContext
        module -> Product
        fields -> [name, description]


        OR:
        paj gen.api:[has_file] context module:module_file_name [fields ...]

        Example:
        ``` paj gen.api ShopContext ProductAd:product_ad name:text description:textarea file:file```

        context -> ShopContext
        module -> ProductAd
        module_file_name -> product_ad
        fields -> [name, description]


        ## PAJ (paj) Help
        # Run command
        ``` $ paj (help | --help | -h)```




  };

    print $help;
}
elsif ( $resource_type =~ "gen.api" ) {

    if ( $resource_type eq "gen.api:has_file" ) {
        $has_file = 1;
        print "Detected has_file set to $has_file \n";
    }

    $base_path = "lib/vendor_web/controllers/api";
    `mkdir -p "$base_path"`;

    # # Make index files
    #  API controller
    $api_controller_file = "$base_path/$module_file_name.ex";
    if ( !( -f "$api_controller_file" ) ) {
        `touch "$api_controller_file"`;
        gen_api_controller("$api_controller_file");

    }
    else {
        print "File Already exists \n";
    }

    $api_json_file = "$base_path/${module_file_name}_json.ex";
    if ( !( -f "$api_json_file" ) ) {

        # API json
        `touch "$api_json_file"`;
        gen_api_json("$api_json_file");

    }
    else {
        print "File Already exists\n";
    }

}

sub gen_api_json {
    my ($file_name) = @_;
    my $template_filename =
      $has_file == 1
      ? "./lib/Phoenix/Templates/schema_json_with_file.txt"
      : "./lib/Phoenix/Templates/schema_json.txt";

    my $gen_fields = "";

    foreach $field (@fields) {
        $gen_fields .= qq{
        $field: ${api_module_lc_singular}.$field,
      };
    }

    my $template_data = gen_from_template($template_filename);
    $template_data =~ s/\{gen_fields\}/$gen_fields/g;
    push_data_to_file( $file_name, $template_data );

}

sub gen_api_controller {
    my ($file_name) = @_;
    my $template_filename =
      $has_file == 1
      ? "./lib/Phoenix/Templates/schema_api_with_file.txt"
      : "./lib/Phoenix/Templates/schema_api.txt";

    my $template_data = gen_from_template($template_filename);
    push_data_to_file( $file_name, $template_data );

}

sub push_data_to_file() {
    my ( $filename, $data ) = @_;
    open my $fh, ">", $filename or die "Cannot open file $filename";
    print $fh "$data \n";
}

sub gen_from_template {
    my ($filename) = @_;
    open my $fh, "<", $filename or die "Cannot open file";
    my $template = "";
    while ( my $line = <$fh> ) {
        $template .= $line;
    }

    my @match_expressions = (
        Regex::Regex->new( { regex => qr/\{context\}/, value => $context } ),
        Regex::Regex->new(
            { regex => qr/\{api_module\}/, value => $api_module }
        ),
        Regex::Regex->new(
            {
                regex => qr/\{api_module_lc_plural\}/,
                value => $api_module_lc_plural
            }
        ),
        Regex::Regex->new(
            {
                regex => qr/\{api_module_lc_singular\}/,
                value => $api_module_lc_singular
            }
        ),

    );

    foreach my $regex_class (@match_expressions) {
        my $regex = $regex_class->regex();
        my $value = $regex_class->value();
        $template =~ s/$regex/$value/g;
    }

    # print("$template \n");

    return $template;

}
