#!/usr/bin/perl

# paj gen.api context apimodule  struct_fields[description:textarea file:file]
# paj gen.api ShopContext ProductAd name:text description:textarea file:file
# paj gen.api context apimodule:apimodule_lc  struct_fields[description:textarea file:file]
# paj gen.api ShopContext ProductAd:product_ad name:text description:textarea file:file

# Run formatter for all files in the project

$resource_type = $ARGV[0];
$context       = $ARGV[1];
@fields        = @ARGV[ 3 .. ( scalar(@ARGV) - 1 ) ];

# Variable
$api_module = $ARGV[2];

# $api_module_lc          = lc($api_module);
$module_file_name       = lc($api_module);
$api_module_lc_plural   = lc($api_module);    # s is added dynamically
$api_module_lc_singular = lc($api_module);

# Default don`t include uploaded file receiving
$has_file = 0;

if ( $api_module =~ /(\b.*):(\b.*)/ ) {
    print("True $api_module $1  :   $2\n");
    $api_module       = $1;
    $module_file_name = $2;

}

if ( $api_module =~ /(\b.*)y/ ) {
    print("True $api_module $1  :   $2\n");

    # $api_module = $1;
    $api_module_lc_plural   = lcfirst("${1}ies");    # s is added dynamically
    $api_module_lc_singular = lcfirst("${1}y");      # s is added dynamically
    $module_file_name       = lcfirst("${1}ies");

}

# print "$resource_type $context $api_module @fields \n";

if (   $resource_type eq "help"
    or $resource_type eq "-h"
    or $resource_type eq "--help" )
{
    $help = qq{
        ## Phoenix Elixir API generator aka paj

        # Syntax
        paj gen.api:[has_file] context module [fields ...]
        has_file -> boolean field generates files with acceptance of a file uploaded to the server


        Example:
        ``` $ paj gen.api ShopContext Product name description ```

        context -> ShopContext
        module -> Product
        fields -> [name, description]


        OR:
        paj gen.api:[has_file] context module:module_file_name [fields ...]

        Example:
        ``` paj gen.api ShopContext ProductAd:product_ad name:text description:textarea file:file```

        context -> ShopContext
        module -> ProductAd
        module_file_name -> product_ad
        fields -> [name, description]


        ## PAJ (paj) Help
        # Run command
        ``` $ paj (help | --help | -h)```




  };

    print $help;
}
elsif ( $resource_type =~ "gen.api" ) {

    if ( $resource_type eq "gen.api:has_file" ) {
        $has_file = 1;
        print "Detected has_file set to $has_file \n";
    }

    $base_path = "lib/vendor_web/controllers/api";
    `mkdir -p "$base_path"`;

    # # Make index files
    #  API controller
    $api_controller_file = "$base_path/$module_file_name.ex";
    if ( !( -f "$api_controller_file" ) ) {
        `touch "$api_controller_file"`;
        gen_api_controller("$api_controller_file");

    }
    else {
        print "File Already exists \n";
    }

    $api_json_file = "$base_path/${module_file_name}_json.ex";
    if ( !( -f "$api_json_file" ) ) {

        # API json
        `touch "$api_json_file"`;
        gen_api_json("$api_json_file");

    }
    else {
        print "File Already exists\n";
    }

}

sub gen_api_json {
    my ($file_name) = @_;
    $imports = qq{
     alias Vendor.$context.{$api_module}
  };

    $defs = qq{
      def index(%{${api_module_lc_plural}: ${api_module_lc_plural}}) do
        %{data: for(${api_module_lc_singular} <- ${api_module_lc_plural}, do: data(${api_module_lc_singular}))}
      end

      def create(_assigns) do
        # dbg(assigns)
        %{response: "success"}
      end

      def update(_assigns) do
        # dbg(assigns)
        %{response: "success"}
      end

      def show(%{${api_module_lc_singular}: ${api_module_lc_singular}}) do
        # dbg(assigns)
        %{data: data(${api_module_lc_singular})}
      end

      def delete(_assigns) do
        # dbg(assigns)
        %{response: "success"}
      end
  };

    $gen_fields = "";

    foreach $field (@fields) {
        $gen_fields .= qq{
        $field: ${api_module_lc_singular}.$field,
      };
    }

    $def_data = $has_file == 1 ? qq{
      def data(%${api_module}{} = $api_module_lc_singular) do
          %{
          # Defaults
            id:  ${api_module_lc_singular}.id,
            created_at:  ${api_module_lc_singular}.inserted_at,
            updated_at: ${api_module_lc_singular}.updated_at,
            $gen_fields
          }
        |> dbg
      end

      #  defp get_url("./" <> path) do
      #     "http://localhost:5000/" <> path
      #   end

      #   defp get_url(_) do
      #     nil
      #   end
    }: qq{
      def data(%${api_module}{} = $api_module_lc_singular) do
          %{
          # Defaults
            id:  ${api_module_lc_singular}.id,
            created_at:  ${api_module_lc_singular}.inserted_at,
            updated_at: ${api_module_lc_singular}.updated_at,
            $gen_fields
          }
        |> dbg
      end
    };

    $module = qq{
      defmodule VendorWeb.Api.${api_module}JSON do
          $imports
          $defs
          $def_data
      end
    };

    push_data_to_file( $file_name, $module );

}

sub gen_api_controller {
    my ($file_name) = @_;
    $imports = $has_file == 1
      ? qq{
      use VendorWeb, :controller
      alias Vendor.$context
      alias VendorProcesses.File.FileUploadSupervisor
  }
      : qq{
      use VendorWeb, :controller
      alias Vendor.$context
  };

    $index = qq{
    def index(conn, _params) do
      ${api_module_lc_plural} = $context.list_${api_module_lc_plural}()

      conn
      |> assign(:${api_module_lc_plural}, ${api_module_lc_plural})
      |> render(:index)
    end
    };

    $show = qq{
      def show(conn, %{"id" => id}) do
          ${api_module_lc_singular} = $context.get_${api_module_lc_singular}!(id)
          dbg(${api_module_lc_singular})

          conn
          |> assign(:${api_module_lc_singular}, ${api_module_lc_singular})
          |> render(:show)
        end
    };

    $create = $has_file == 1
      ? qq{
        def create(conn, %{"uuid" => uuid} = params) do
            {file_path, _mime_type} = FileUploadSupervisor.get_uploaded_file_path(uuid)
            dbg(file_path)

            # E.g. Map.put(params, "poster_image_path", file_path)

            Map.put(params, file_field, file_path)
            |> $context.create_${api_module_lc_singular}()
            |> dbg()

            render(conn, :create)
          end
    }
      : qq{
        def create(conn, params) do
            params
            |> $context.create_${api_module_lc_singular}()
            |> dbg()

            render(conn, :create)
          end
    };

    $update = $has_file == 1 ? qq{
        def update(conn, %{"id" => id, "uuid" => uuid} = attrs) do
          dbg(attrs)
          ${api_module_lc_singular} = $context.get_${api_module_lc_singular}!(id)

          case FileUploadSupervisor.get_uploaded_file_path(uuid) do
            nil ->
              ${api_module_lc_singular}
              |> $context.update_${api_module_lc_singular}(attrs)
              |> dbg()

            {file_path, _mime_type} ->
              ${api_module_lc_singular}
              |> $context.update_${api_module_lc_singular}(Map.put(attrs, file_field, file_path))
              |> dbg()
          end

          render(conn, :update)
        end
    } : qq{
        def update(conn, %{"id" => id} = params) do

          ${api_module_lc_singular} = $context.get_${api_module_lc_singular}!(id)

          ${api_module_lc_singular}
          |> $context.update_${api_module_lc_singular}(params)
          |> dbg()


          render(conn, :update)
        end
    };

    $delete = qq{
      def delete(conn, %{"id" => id} = params) do
        dbg(params)
        ${api_module_lc_singular} = $context.get_${api_module_lc_singular}!(id)

        ${api_module_lc_singular}
        |> $context.delete_${api_module_lc_singular}()

        render(conn, :delete)
      end
    };

    $module = qq{
      defmodule VendorWeb.Api.$api_module do
            $imports
            $index
            $show
            $create
            $update
            $delete

      end
    };

    push_data_to_file( $file_name, $module );

}

sub push_data_to_file() {
    my ( $filename, $data ) = @_;
    open my $fh, ">", $filename or die "Cannot open file $filename";
    print $fh "$data \n";
}
